
spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/DemoIMT
        username: postgres
        password: 1148
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                globally_quoted_identifiers: true
                format_sql: true

        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect